language: cpp

compiler:
  - gcc
  
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
